import { SIGNUP_ID, SUCCESS_ID } from "../constants"

export const SignUpFormSnapShot = '<div class="sign-up--wrapper"><div class="illustration-sign-up-mobile"><img class="illustration-sign-up-mobile--img" src="./assets/images/illustration-sign-up-mobile.svg"></div><div class="display-flex"><div class="sign-up"><h1 class="sign-up--header-text">Stay Updated!</h1><div class="mb-1">Join 60,000+ product managers receiving monthly updates on:</div><div><div class="mb-1"><i class="icon icon-sm icon-list mr-1"></i><span>Product discovery and building what matters</span></div><div class="mb-1"><i class="icon icon-sm icon-list mr-1"></i><span>Measuring to ensure updates are a success</span></div><div class="mb-1"><i class="icon icon-sm icon-list mr-1"></i><span>And much more!</span></div></div><form action="" class="sign-up--form" id="sign-up--form"><label for="sign-up--form--email-address" class="sign-up--form--label float float-left mb-1">Email address</label> <label for="sign-up--form--email-address" class="sign-up--form--label float float-right invalid">Valid email required</label> <input required="required" name="email-address" id="sign-up--form--email-address" class="sign-up--form--input-field curvy mb-1" type="email" placeholder="email@company.com"><button class="button curvy sign-up--form--submit-button">Subscribe to monthly newsletter</button></form></div><div class="illustration-sign-up"><img class="illustration-sign-up--img" src="./assets/images/illustration-sign-up-desktop.svg"></div></div></div><div class="attribution">Challenged by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>. Coded by <a href="https://github.com/HTWKS">Hung Duong</a>.</div>'
export const SuccessFormSnapShot = '<div class="success--wrapper"><i class="icon icon-lg icon-success"></i><h1 class="success--header-text">Thanks for subscribing!</h1><div class="mb-1">A confirmation email has been sent to <b><span name="sign-up-form--email"></span></b>. Please open it and click the button inside to confirm your subscription.</div><button class="button curvy success--button">Dismiss message</button></div>'
export const GlobalCSSSnapShot = '@font-face{font-family:Roboto;src:url(../assets/fonts/Roboto-Regular.ttf)}@font-face{font-family:Roboto;font-weight:700;src:url(../assets/fonts/Roboto-Bold.ttf)}body{--tomato:#ff6257;--dark-slate-grey:#242742;--charcoal-grey:#36384e;--light-tomato:#fae9e7;--grey:#9294a0;--white:#fff;--text-size:16px;font-family:Roboto}.float{display:inline-block}.float-left{float:left}.float-right{float:right}.invalid{color:var(--tomato);visibility:hidden}.icon-list{background:url(../assets/images/icon-list.svg)}.icon-success{background:url(../assets/images/icon-success.svg)}.icon{background-repeat:no-repeat;background-size:cover;display:inline-block}.icon-lg{height:calc(var(--text-size)*8);width:calc(var(--text-size)*8)}.icon-sm{height:calc(var(--text-size)*2);width:calc(var(--text-size)*2)}.button{background:var(--dark-slate-grey);border:none;color:var(--white);cursor:pointer;font-size:1em;padding:var(--text-size)}.button:hover{background:var(--tomato)}.mb-1{margin-bottom:var(--text-size)}.mr-1{margin-right:var(--text-size)}.curvy{border-radius:1vw}'
export const SignUpFormCSSSnapShot = '.attribution{font-size:11px;text-align:center}.attribution a{color:#3e52a3}.sign-up--wrapper{padding:3vw;width:100%}.display-flex{display:flex}.sign-up{box-sizing:border-box;color:var(--charcoal-grey);font-size:var(--text-size);margin:auto;padding:2vw}.illustration-sign-up,.sign-up{width:50%}.illustration-sign-up-mobile{display:none}@media only screen and (max-width:375px){.sign-up{width:100%}.illustration-sign-up{width:0}.illustration-sign-up-mobile{display:block}}.sign-up--header-text{font-size:3.5em;margin-top:0}.sign-up--form{width:90%}.sign-up--form>button,input{box-sizing:border-box}.sign-up--form--input-field{border-style:solid;display:block;font-size:1em;padding:var(--text-size);width:100%}.sign-up--form:invalid>label.invalid{visibility:visible}.sign-up--form--input-field:valid{border-color:var(--grey)}.sign-up--form--input-field:invalid{background-color:var(--light-tomato);border-color:var(--tomato);color:var(--tomato)}.sign-up--form--submit-button{width:100%}.sign-up--form--label{font-size:.75em;font-weight:700}.illustration-sign-up--img{width:100%}'
export const SuccessFormCSSSnapShot = '.success--wrapper{margin:auto;width:400px}.success--header-text{font-size:3.5em}.success--button{width:100%}@media only screen and (max-width:375px){.success--wrapper{height:100%;width:100%}.success--button{margin-bottom:auto;margin-top:100%}}'

export function getSignUpFormDom() {
    const parser = new DOMParser();
    const signUpFormDom = parser.parseFromString(SignUpFormSnapShot, 'text/html');
    (signUpFormDom.body.firstChild as HTMLElement).id = SIGNUP_ID;
    return signUpFormDom;
}

export function getSuccessFormDom() {
    const parser = new DOMParser();
    const successFormDom = parser.parseFromString(SuccessFormSnapShot, 'text/html');
    (successFormDom.body.firstChild as HTMLElement).id = SUCCESS_ID;
    return successFormDom;
}