name: Learn-Front-End
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Run all test for newsletter-sign-up-with-success-message
        working-directory: ./newsletter-sign-up-with-success-message-main
        run: ./scripts/run-all-local-tests.sh

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install and Build project
        working-directory: ./newsletter-sign-up-with-success-message-main/src
        run: npm install && npm run-script build

      - name: Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./newsletter-sign-up-with-success-message-main/src/out